---
name: build-cyprus-map
on:
  push:
  workflow_dispatch:
jobs:
  build-cyprus-map:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print tag
        run: |
          echo Git ref: $GITHUB_REF
